apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: st--tpcc-prepare
spec:
  params:
    - name: run-id
      type: string
      default: st--tpcc-prepare
  workspaces:
    - name: manifest
  tasks:
    - name: env-prepare
      taskRef:
        name: st--lib--env-prepare
      workspaces:
        - name: manifest
          workspace: manifest
      params:
        - name: trr-name
          value: "$(params.run-id)"
        - name: tct-name
          value: "$(params.run-id)"
        - name: trr-manifest
          value: |
            apiVersion: naglfar.pingcap.com/v1
            kind: TestResourceRequest
            metadata:
              name: $(params.run-id)
            spec:
              items:
                - name: workload
                  spec: {memory: 32GB, cores: 16}
                - name: ctl
                  spec: {memory: 8GB, cores: 4}
                - name: proxy
                  spec: {memory: 16GB, cores: 8}
                - name: db-pd-1
                  spec: {memory: 16GB, cores: 16}
                - name: db-pd-2
                  spec: {memory: 16GB, cores: 16}
                - name: db-pd-3
                  spec: {memory: 16GB, cores: 16}
                - name: kv1
                  spec: {memory: 16GB, cores: 8, disks: {disk1: {kind: nvme, size: 3TB, mountPath: /disk1}}}
                - name: kv2
                  spec: {memory: 16GB, cores: 8, disks: {disk1: {kind: nvme, size: 3TB, mountPath: /disk1}}}
                - name: kv3
                  spec: {memory: 16GB, cores: 8, disks: {disk1: {kind: nvme, size: 3TB, mountPath: /disk1}}}
                - name: kv4
                  spec: {memory: 16GB, cores: 8, disks: {disk1: {kind: nvme, size: 3TB, mountPath: /disk1}}}
                - name: kv5
                  spec: {memory: 16GB, cores: 8, disks: {disk1: {kind: nvme, size: 3TB, mountPath: /disk1}}}
        - name: tct-manifest
          value: |
            apiVersion: naglfar.pingcap.com/v1
            kind: TestClusterTopology
            metadata:
              name: $(params.run-id)
            spec:
              resourceRequest: $(params.run-id)
              tidbCluster:
                global:
                  deployDir: "/disk1/deploy"
                  dataDir: "/disk1/data"
                version:
                  version: v4.0.10
                tikv:
                  - host: kv1
                  - host: kv2
                  - host: kv3
                  - host: kv4
                  - host: kv5
                tidb:
                  - host: db-pd-1
                  - host: db-pd-2
                  - host: db-pd-3
                pd:
                  - host: db-pd-1
                  - host: db-pd-2
                  - host: db-pd-3
                control: ctl
                monitor:
                  - host: ctl
                    port: 9090
                grafana:
                  - host: ctl
                    port: 3000
                haProxy:
                  host: proxy
                  port: 3306
                  version: 2.0.20
                  config: |-
                    global
                      daemon
                      maxconn 4000
                      nbproc 8
                    defaults
                      retries 2
                      timeout connect 2s
                      timeout client  30000s
                      timeout server  30000s
                    listen admin_stats
                      bind 0.0.0.0:8080
                      mode http
                      option httplog
                      stats refresh 30s
                      stats realm Haproxy
                      stats uri /haproxy
                      stats auth admin:admin
    - name: tpcc-prepare
      taskRef:
        name: st--workload-tpcc--prepare
      runAfter:
        - env-prepare
      workspaces:
        - name: manifest
          workspace: manifest
      params:
        - name: workload-name
          value: "$(params.run-id)"
        - name: tct-name
          value: "$(params.run-id)"
        - name: trr-name
          value: "$(params.run-id)"
        - name: threads
          value: "16"
        - name: warehouses
          value: "30000"
